### PR TITLE
Win32: change serdev.c enough to compile on Windows. Fix warnings and errors

### PR DESCRIPTION
**Pull request by ruevs**
by using ANSI C functions instead of obsolete POSIX ones.

### CODE REVIEW

**Comment by jtsiomb** [comment]
At the very least these changes need to be conditional for windows only. The leading-underscore variants of the POSIX calls are certainly not ANSI C, they are a microsoft thing. But also, I'm not convinced that by just changing write to _write will make this work on windows. I would imagine we'd need to go for a `CreateFile`, `MsgWaitForMultipleObjects` approach. Did you try this with a serial device, beyond just coaxing the compiler to accept it?

**Comment by ruevs** [comment]
The only device I have is a SpaceExplorer (USB) so I can not test this. That is why I left it as a separate pull request.

The only goal here was to make it compile and remove the errors, reduce the warnings (when compiling with Microsoft Visual Studio Community 2019 Version 16.8.5). 

As for `_open` etc... you are right ["_open and _wopen are Microsoft extensions. For more compatibility information, see Compatibility."](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=msvc-160#requirements) so I'll rework it.

**Comment by jtsiomb** [comment]
Don't worry about it, for now just rename `serdev.c` to `serdev_unix.c`, and remove it from the windows build (are you using your own visual studio project files? or are you building with mingw?). Then add a `serdev_win32.c` with an empty `spndev_ser_open` function that always returns -1. And also enclose the whole file in an `#ifdef WIN32` for now, until I fix the makefile to conditionally add platform-specific files to the build. That should be sufficient for now.

**Comment by ruevs** [comment]
Closing since https://github.com/FreeSpacenav/libspnavdev/pull/4 includes this.

**Pull request closed without merging**
