### PR TITLE
Implement support for 3Dconnexion USB 6DOF controllers. SpaceMouse etc.

### PR DESCRIPTION
**Pull request by ruevs**
Hi First of all - great foundation. After getting a SpaceExplorer I was able to implement the USB support in about 10 hours.

It is using `hidapi` as a HID access library.

Tested on Windows with SpaceExplorer. Should work on Linux.
Needs hid.c and hidapi.h from here: https://github.com/libusb/hidapi

I did not add `hidapi` as submodule or change the build system, since I am not sure how you would like to handle this.

### CODE REVIEW

**Comment by jtsiomb** [comment]
Wow, nice! I wasn't expecting any contributions in this project yet. I'll pull this in a local branch and test it on GNU/Linux, and Iater I'll have to review it.

The problem is that this project is completely swapped out for me right now, as I'm working on other things currently, and I need to do a full context switch back to it, remember and re-examine where I was going with it, before I can decide whether to merge this as is, or if I want something changed, what to do with the HID library, and so on. This is an artifact of this code being very early stage experiment (I can't even remember if the code I had here was actually working, or I was just spitballing interfaces and API structure at this point). And not having finalized the structure, I don't want to commit before thinking it through.

So what I'm saying is it might take me some time before I decide how to proceed. I hope you're not in a hurry. In any case I really appreciate it. If it seems like it's taking too long to switch back to this, at the very least I'll pull everything in a public branch, so that it will be available to others.

Feel free to ping me again in a few weeks (either here, through email, or through the mailing list) if I haven't done anything, because I don't want to forget about it for 6 months.

**Comment by ruevs** [comment]
Thanks for looking! :-)

> Wow, nice! I wasn't expecting any contributions in this project yet. I'll pull this in a local branch and test it on GNU/Linux, and Iater I'll have to review it.

I decided to start from your code sine at first I decided to write my own, then I decided to search and found at least 10 raw HID SpaceMouse drivers/toys/examples in different languages floating around. And yours was the one in `C` that I liked most (and you having written `spacenavd` helped), so I decided to build on it.

> The problem is that this project is completely swapped out for me right now, as I'm working on other things currently, and I need to do a full context switch back to it, remember and re-examine where I was going with it, before I can decide whether to merge this as is, or if I want something changed, what to do with the HID library, and so on.

It is clear that it was an early work in progress and that is why I tried to make the changes as minimal as possible.

> This is an artifact of this code being very early stage experiment (I can't even remember if the code I had here was actually working, or I was just spitballing interfaces and API structure at this point). And not having finalized the structure, I don't want to commit before thinking it through.

It was not compiling (not only because of Windows e.g. [missing functions](https://github.com/ruevs/libspnavdev/blob/FixWin32Build/src/serdev.c#L260)) :-) But it looks good ;-)

> So what I'm saying is it might take me some time before I decide how to proceed. I hope you're not in a hurry.

Not at all. I can "scratch my itch" in my fork ;-)

> In any case I really appreciate it. If it seems like it's taking too long to switch back to this, at the very least I'll pull everything in a public branch, so that it will be available to others.

No problem, take your time.  I'd appreciate your feedback.

In the meantime if someone wants to try it here is a (release) binary for Windows to play with. [libspnavtest.zip](https://github.com/FreeSpacenav/libspnavdev/files/5980201/libspnavtest.zip)
And the corresponding source code [libspnavUSBWin32Src.zip](https://github.com/FreeSpacenav/libspnavdev/files/5980288/libspnavUSBWin32Src.zip) with all three of my pull requests and a visual Studio project in `libspnavUSBWin32Src\buildvs\libspnavtest.vcxproj`

> Feel free to ping me again in a few weeks (either here, through email, or through the mailing list) if I haven't done anything, because I don't want to forget about it for 6 months.

OK I will.  Is this https://sourceforge.net/p/spacenav/mailman/spacenav-devel/ the correct mailing list?

**Comment by jtsiomb** [comment]
> OK I will. Is this https://sourceforge.net/p/spacenav/mailman/spacenav-devel/ the correct mailing list?

Yes. That's the development mailing list for the spacenav project.

**Comment by ruevs** [comment]
Closing since https://github.com/FreeSpacenav/libspnavdev/pull/4 includes this.

**Pull request closed without merging**
